// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyIo4gt_RvirD6drE1FxIhc0lhepxVw1g',
    appId: '1:196900937:web:815bece36358ec96b7a798',
    messagingSenderId: '196900937',
    projectId: 'appcastro-66262',
    authDomain: 'appcastro-66262.firebaseapp.com',
    storageBucket: 'appcastro-66262.firebasestorage.app',
    measurementId: 'G-9WQ26ZV902',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvFE6Xlep-iTfsz31_NSXlqEazMRDHsvk',
    appId: '1:196900937:android:aa356bae6b10748eb7a798',
    messagingSenderId: '196900937',
    projectId: 'appcastro-66262',
    storageBucket: 'appcastro-66262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgpf0Z2EDAwnphJiC0Wnh_SPj9ynkByxk',
    appId: '1:196900937:ios:f5672813f1b8e824b7a798',
    messagingSenderId: '196900937',
    projectId: 'appcastro-66262',
    storageBucket: 'appcastro-66262.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgpf0Z2EDAwnphJiC0Wnh_SPj9ynkByxk',
    appId: '1:196900937:ios:f5672813f1b8e824b7a798',
    messagingSenderId: '196900937',
    projectId: 'appcastro-66262',
    storageBucket: 'appcastro-66262.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyIo4gt_RvirD6drE1FxIhc0lhepxVw1g',
    appId: '1:196900937:web:e95887cd62bbacc8b7a798',
    messagingSenderId: '196900937',
    projectId: 'appcastro-66262',
    authDomain: 'appcastro-66262.firebaseapp.com',
    storageBucket: 'appcastro-66262.firebasestorage.app',
    measurementId: 'G-82BMG0JE6M',
  );
}
