name: project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  pdf: ^3.11.3
  path_provider: ^2.1.4
  file_saver: ^0.2.13
  printing: ^5.12.0
  window_size: ^0.1.0
  intl: ^0.20.2
  pdf_widget_wrapper: ^1.0.4
  http: ^1.3.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  provider: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - lib/images/logo1.png
    - lib/images/logo2.png
    - assets/fonts/static/Roboto-Regular.ttf